version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    ports:
      - "6007:3000"
    volumes:
      - /root/docker/prometheus/conf/grafana:/etc/grafana
      - /root/docker/prometheus/data/prometheus/grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - net-prometheus
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root
    ports:
      - "6008:9090"
    volumes:
      - /root/docker/prometheus/conf/prometheus:/etc/prometheus
      - /root/docker/prometheus/data/prometheus/prometheus_db:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - net-prometheus
    restart: always

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    user: root
    ports:
      - "6009:9091"
    volumes:
      - /root/docker/prometheus/data/prometheus/pushgateway_data:/var/lib/pushgateway
    restart: always

  alertmanager:
    image: prom/alertmanager
    hostname: alertmanager
    container_name: alertmanager
    user: root
    ports:
      - "6010:9093"
    volumes:
      - /root/docker/prometheus/conf/alertmanager:/etc/alertmanager
      - /root/docker/prometheus/data/prometheus/alertmanager_data:/var/lib/alertmanager
    restart: always

networks:
  net-prometheus: