version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    hostname: "portainer"
    ports:
      - 9000:9000
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker/portainer/data:/data
      - /root/docker/portainer/public:/public
    restart: always
  mysql:
    container_name: mysql
    image: swr.cn-north-4.myhuaweicloud.com/silverfenrir/mysql:latest
    hostname: "mysql"
    ports:
      - 3306:3306
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: MySQL-7cb1dc18
    volumes:
      - /root/docker/mysql/conf:/etc/mysql
      - /root/docker/mysql/logs:/var/log/mysql
      - /root/docker/mysql/data:/var/lib/mysql
      - /root/docker/mysql/files:/var/lib/mysql-files
    restart: always
  python:
    container_name: python
    image: swr.cn-north-4.myhuaweicloud.com/silverfenrir/python3:latest
    hostname: "python"
    ports:
      - 5000:5000
      - 5001:5001
      - 5002:5002
      - 5003:5003
      - 5004:5004
    network_mode: bridge
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/projects/python:/home/projects
      - /root/docker/python/logs:/var/log/
    command:
      - sh
      - -c
      - |
          yum -y install gcc  gcc-c++ zlib zlib-devel openssl openssl-devel pcre pcre-devel geoipupdate gd libXpm libxslt sqlite-devel
          pip install uwsgi
          cd /home/projects/Fisher
          cp -f /home/projects/fisher-secure.py app/config/secure.py
          pipenv install
          /usr/local/python3/bin/uwsgi uwsgi.ini &
          /sbin/init
    privileged: true
    restart: always
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    hostname: "jenkins"
    user: root
    ports:
      # 发布端口
      - 6001:8080
      # 基于 JNLP 的 Jenkins 代理通过 TCP 端口 50000 与 Jenkins master 进行通信
      - 50000:50000
    network_mode: bridge
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: -Djava.util.logging.config.file=/var/jenkins_home/log.properties
    volumes:
      - /root/docker/jenkins/jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime
    restart: always
  minio:
    container_name: minio
    image: minio/minio
    hostname: "minio"
    ports:
      - 6002:9000 # api 端口
      - 6003:9001 # 控制台端口
    network_mode: bridge
    environment:
      MINIO_ROOT_USER: fenrir    #管理后台用户名
      MINIO_ROOT_PASSWORD: Minio_7cb1dc18 #管理后台密码，最小8个字符
      MINIO_SERVER_URL: http://mio.silver-fenrir.cn # 更改分享主机名（域名、ip/端口）
    volumes:
      - /root/docker/minio/data:/data               #映射当前目录下的data目录至容器内/data目录
      - /root/docker/minio/config:/root/.minio/     #映射配置目录
    command: server --address ':9000' --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true
    restart: always