version: '3'
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    hostname: "filebrowser"
    ports:
      - "6004:80"
    network_mode: bridge
    volumes:
      - /root/docker/filebrowser/root:/root
      - /root/docker/jenkins/jenkins_home/workspace/download@2:/root/jenkins_download_ci
      - /root/docker/filebrowser/home:/home
      - /root/docker/filebrowser/logs:/var/log
      - /root/docker/filebrowser/filebrowser.db:/etc/filebrowser/filebrowser.db
      - /root/docker/filebrowser/.filebrowser.json:/.filebrowser.json
      - /etc/localtime:/etc/localtime:ro
    restart: always