version: '3'
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    hostname: "filebrowser"
    ports:
      - "6004:80/tcp"
    network_mode: bridge
    volumes:
      - /root/docker/filebrowser/srv:/srv
      - /root/docker/filebrowser/branding:/home/branding
      - /root/docker/filebrowser/filebrowser.db:/database.db
      - /root/docker/filebrowser/.filebrowser.json:/.filebrowser.json
      - /etc/localtime:/etc/localtime:ro
    restart: always