version: '3'

services:
  gerrit:
    container_name: gerrit-ldap-gerrit
    image: gerritcodereview/gerrit
    ports:
      - "29418:29418"
      - "8082:8080"
    depends_on:
      - ldap
    volumes:
      - /home/docker/gerrit/etc:/var/gerrit/etc
      - /home/docker/gerrit/git:/var/gerrit/git
      - /home/docker/gerrit/db:/var/gerrit/db
      - /home/docker/gerrit/index:/var/gerrit/index
      - /home/docker/gerrit/cache:/var/gerrit/cache
    environment:
      - CANONICAL_WEB_URL=http://localhost
    # command: init

  ldap:
    container_name: gerrit-ldap-ldap
    image: osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=secret
    volumes:
      - /home/docker/gerrit/ldap/var:/var/lib/ldap
      - /home/docker/gerrit/ldap/etc:/etc/ldap/slapd.d

  ldap-admin:
    container_name: gerrit-ldap-ldap-admin
    image: osixia/phpldapadmin
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap