version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    hostname: "jenkins"
    user: root
    ports:
      # 发布端口
      - 6001:8080
      # 基于 JNLP 的 Jenkins 代理通过 TCP 端口 50000 与 Jenkins master 进行通信
      - 50000:50000
    network_mode: bridge
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: -Djava.util.logging.config.file=/var/jenkins_home/log.properties
    volumes:
      - /root/docker/jenkins/jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime
    restart: always