version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    user: root
    networks:
      - kafka_net
    ports:
      - '2181:2181'
    environment:
      # 匿名登录--必须开启
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - /home/docker/kafka/zookeeper:/bitnami/zookeeper
    restart: always

  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    user: root
    networks:
      - kafka_net
    ports:
      - '9092:9090'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9090
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: always
    depends_on:
      - zookeeper

  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka2
    user: root
    networks:
      - kafka_net
    ports:
      - '9093:9090'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9090
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: always
    depends_on:
      - zookeeper

  kafka3:
    image: bitnami/kafka:latest
    container_name: kafka3
    user: root
    networks:
      - kafka_net
    ports:
      - '9094:9090'
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9090
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: always
    depends_on:
      - zookeeper


networks:
  kafka_net:
    driver: bridge