version: '3'

services:
#######################
# 执行数据库迁移
######################
  kong-migration:
    image: kong:latest
    container_name: kong-migration
    command: "kong migrations bootstrap"
    networks: 
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresql-database
      KONG_PG_DATABASE: kong
      KONG_PG_PASSWORD: kNMjM8YlkCJXj7U5xu3vkisTaTbUNXfT
    links: 
      - postgresql-database #连接的是postgresql-database服务的
    depends_on:
      - postgresql-database #依赖于postgresql-database服务
    restart: on-failure

#####################
# kong gateway
#####################
  kong:
    image: kong:latest
    container_name: kong
    hostname: kong
    networks:
      - kong-net
    depends_on:
      - kong-migration
      - postgresql-database
    ports:
      - "18001:8001"
      - "8080:8000"
      - "8443:8443"
      - "8444:8444"
    environment:
      TZ: Asia/Shanghai
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresql-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kNMjM8YlkCJXj7U5xu3vkisTaTbUNXfT
      # KONG_CASSANDRA_CONTACT_POINTS: postgres-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8443 ssl
    restart: always

#######################
#以下两个是konga  GUI
#######################
  konga-prepare:
    image: pantsel/konga:latest
    container_name: konga-prepare
    command: "-c prepare -a postgres -u postgresql://kong:kNMjM8YlkCJXj7U5xu3vkisTaTbUNXfT@postgresql-database:5432/konga"  #注意是用户名：密码@数据库服务名称：端口
    networks:
      - kong-net
    restart: on-failure
    links:
      - postgresql-database
    depends_on:
      - kong        #依赖kong服务
      - postgresql-database #依赖postgres-database服务

  konga:
    image: pantsel/konga:latest
    container_name: konga
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: postgresql-database
      DB_USER: kong
      DB_DATABASE: konga
      DB_PASSWORD: kNMjM8YlkCJXj7U5xu3vkisTaTbUNXfT #必须加上密码，不然会失败
    depends_on:
      - kong
      - postgresql-database
    ports:
      - "8337:1337"
    restart: always

networks:
  kong-net:
    external: true
