version: '3'
services:
  minio:
    container_name: minio
    image: minio/minio
    hostname: "minio"
    ports:
      - "6002:9000" # api 端口
      - "6003:9001" # 控制台端口
    network_mode: bridge
    environment:
      MINIO_ROOT_USER: fenrir    #管理后台用户名
      MINIO_ROOT_PASSWORD: Minio_7cb1dc18 #管理后台密码，最小8个字符
      MINIO_SERVER_URL: https://mio.silver-fenrir.cn # 更改分享主机名（域名、ip/端口）
    volumes:
      - /root/docker/minio/data:/data               #映射当前目录下的data目录至容器内/data目录
      - /root/docker/minio/config:/root/.minio/     #映射配置目录
    command: server --address ':9000' --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true
    restart: always