version: '3'
services:
  mysql:
    container_name: mongodb
    image: 	mongo:6.0
    hostname: "mongodb"
    ports:
      - "8117:27017"
    network_mode: bridge
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=N%zM2UWDUmXV
    volumes:
      - /mnt/data/docker/mongodb/data:/data/db
    restart: always