version: '3'
services:
  mysql:
    container_name: mysql
    image: 	mysql:latest	
    hostname: mysql
    networks:
      - inner_net
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: MLAdmin2307
    volumes:
      - /mnt/data/docker/mysql/conf:/etc/mysql
      - /mnt/data/docker/mysql/logs:/var/log/mysql
      - /mnt/data/docker/mysql/data:/var/lib/mysql
      - /mnt/data/docker/mysql/files:/var/lib/mysql-files
      - /mnt/data/docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
    restart: always

networks:
  inner_net:
    external: true
