version: '3'
services:
  netdata:
    container_name: netdata
    image: netdata/netdata
    hostname: "netdata"
    ports:
      - "6006:19999"
    network_mode: bridge
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /root/docker/netdata/config:/etc/netdata
      - /root/docker/netdata/lib:/var/lib/netdata
      - /root/docker/netdata/cache:/var/cache/netdata
      - /root/docker/netdata/web:/usr/share/netdata/web
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - DOCKER_USR=root
      - NETDATA_CLAIM_TOKEN=VXcFk9wPDgNBtJazBZxt34AeRjz9fJtq25ss4gdj6lb4NIM5ltvMgTtMLp_0Y9okdUR1opeJLvO4dkZUMHYDwZ0jJmgQdvKRDgRAIzeTLfsxsN6WgoHK8kJLRxgmfz90ITX_Z_M
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=
