version: '3'
services:
  netdata:
    container_name: netdata
    image: netdata/netdata
    hostname: "netdata"
    ports:
      - 19999:19999
    network_mode: bridge
    environment:
      - DOCKER_USR=root
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /root/docker/netdata/config:/etc/netdata
      - /root/docker/netdata/lib:/var/lib/netdata
      - /root/docker/netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    restart: always
