version: '3.5'

services:
  ops-db:
    image: registry.cn-hangzhou.aliyuncs.com/veops/mysql:latest
    container_name: ops-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 'A6ZcChIY1b861H9hrC6fZhRvpuPeM9yS'
    volumes:
      - /mnt/data/docker/oneops/db-data:/var/lib/mysql
      - /mnt/data/docker/oneops/docs/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - /mnt/data/docker/oneops/docs/create-users.sql:/docker-entrypoint-initdb.d/1-create-users.sql
      - /mnt/data/docker/oneops/docs/ops.sql:/docker-entrypoint-initdb.d/ops.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      new:
        aliases:
          - mysql
    ports:
      - '3307:3306'

  ops-cache:
    image: registry.cn-hangzhou.aliyuncs.com/veops/redis:latest
    container_name: ops-cache
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /mnt/data/docker/oneops/redis-data:/data
    networks:
      new:
        aliases:
          - redis

  cmdb-api:
    image: registry.cn-hangzhou.aliyuncs.com/veops/cmdb-api:2.4.3
    container_name: cmdb-api-ops
    volumes:
      - /mnt/data/docker/oneops/docs/.env:/data/apps/cmdb/.env
      - /mnt/data/docker/oneops/docs/app.py:/data/apps/cmdb/api/lib/perm/acl/app.py
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: ops-db:3306, ops-cache:6379
    command:
      - /bin/sh
      - -c
      - |
        sed -i "s#USE_ACL = False#USE_ACL = True#g" settings.py
        /wait
        flask db-setup
        flask common-check-new-columns
        gunicorn --workers=4 autoapp:app -b 0.0.0.0:5000 -D
        celery -A celery_worker.celery worker -E -Q one_cmdb_async --autoscale=4,1 --logfile=one_cmdb_async.log -D
        celery -A celery_worker.celery worker -E -Q acl_async --logfile=one_acl_async.log --autoscale=2,1 -D
        nohup flask cmdb-trigger > trigger.log 2>&1 &
        flask cmdb-init-cache
        flask cmdb-init-acl
        flask init-import-user-from-acl
        flask init-department
        flask cmdb-counter > counter.log 2>&1

    depends_on:
      - ops-db
      - ops-cache
    networks:
      new:
        aliases:
          - cmdb-api

  oneterm-api:
    image: registry.cn-hangzhou.aliyuncs.com/veops/oneterm-api:24.3
    container_name: oneterm-api-ops
    volumes:
      - /mnt/data/docker/oneops/file-data:/replay
      - /mnt/data/docker/oneops/docs/api.yaml:/oneterm/config.yaml
    depends_on:
      - ops-db
      - ops-cache
      - oneterm-guacd
    restart: always
    networks:
      new:
        aliases:
          - oneterm-api

  oneterm-ssh:
    image: registry.cn-hangzhou.aliyuncs.com/veops/oneterm-ssh:24.3.1
    container_name: oneterm-ssh-ops
    ports:
      - "8081:12228"
    restart: always
    tty: true
    volumes:
      - /mnt/data/docker/oneops/docs/ssh.yaml:/oneterm/config.yaml
      - /mnt/data/docker/oneops/docs/scripts/entrypoint.sh:/oneterm/entrypoint.sh
      - /mnt/data/docker/oneops/ssh-data:/root/.ssh
    entrypoint: ./entrypoint.sh
    depends_on:
      - oneterm-api
    networks:
      new:
        aliases:
          - oneterm-ssh

  ops-ui:
    image: registry.cn-hangzhou.aliyuncs.com/veops/ops-ui:24.4.2
    container_name: ops-ui
    depends_on:
      - oneterm-api
    environment:
      TZ: Asia/Shanghai
      ONETERM_API_HOST: oneterm-api:8080
      CMDB_API_HOST: cmdb-api:5000
      NGINX_PORT: 80
    volumes:
      - /mnt/data/docker/oneops/docs/nginx.cmdb.conf.example:/etc/nginx/conf.d/nginx.oneterm.conf.example
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        envsubst '$$ONETERM_API_HOST  $$CMDB_API_HOST $$NGINX_PORT' < /etc/nginx/conf.d/nginx.oneterm.conf.example > /etc/nginx/conf.d/oneterm.conf
        nginx -g  'daemon off;'
    networks:
      - new
    ports:
      - "8080:80"
  
  oneterm-guacd:
    image: registry.cn-hangzhou.aliyuncs.com/veops/oneterm-guacd:24.3
    container_name: oneterm-guacd
    restart: always
    user: root
    volumes:
      - /mnt/data/docker/oneops/file-data:/replay
    networks:
      new:
        aliases:
          - oneterm-guacd

networks:
  new:
    driver: bridge
    name: ops_network
    ipam:
      config:
        - subnet: 172.36.0.0/24
