version: '3'
services:
  portainer:
    container_name: portainer-ce
    image: portainer/portainer-ce
    hostname: "portainer"
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker/portainer/data:/data
      - /root/docker/portainer/public:/public
    restart: always