version: "3"

services:
    monitor-prometheus:
        image: prom/prometheus
        container_name: monitor-prometheus
        hostname: monitor-prometheus
        restart: always
        user: root
        volumes:
            - /mnt/data/docker/monitor/prometheus/conf:/etc/prometheus
            - /mnt/data/docker/monitor/prometheus/data:/prometheus
        ports:
            - "8003:9090"
        networks:
            - monitor
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"

    monitor-alertmanager:
        image: prom/alertmanager
        container_name: monitor-alertmanager
        hostname: monitor-alertmanager
        user: root
        restart: always
        volumes:
            - /mnt/data/docker/monitor/alertmanager/conf:/etc/alertmanager
        ports:
            - "8004:9093"
        networks:
            - monitor

    monitor-grafana:
        image: grafana/grafana
        container_name: monitor-grafana
        hostname: monitor-grafana
        user: root
        restart: always
        ports:
            - "8005:3000"
        volumes:
            - /mnt/data/docker/monitor/grafana/data:/var/lib/grafana
            - /mnt/data/docker/monitor/grafana/config:/etc/grafana
        networks:
            - monitor

    monitor-node-exporter:
        image: quay.io/prometheus/node-exporter
        container_name: monitor-node-exporter
        hostname: monitor-node-exporter
        restart: always
        user: root
        ports:
            - "8100:9100"
        networks:
            - monitor

    monitor-consul:
        image: consul:1.9.4
        container_name: monitor-consul
        restart: always
        user: root
        ports:
            - "8101:8500"
        volumes:
            - /mnt/data/docker/monitor/consul/data:/consul/data
        command: [agent, -server, -ui, -client=0.0.0.0, -bootstrap-expect=1]

networks:
    monitor:
        driver: bridge
