version: '3'
services:
  python:
    container_name: python
    image: swr.cn-north-4.myhuaweicloud.com/silverfenrir/python3:latest
    hostname: "python"
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
    network_mode: bridge
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/projects/python:/home/projects
      - /root/docker/python/logs:/var/log/
    command:
      - sh
      - -c
      - |
          yum -y install gcc  gcc-c++ zlib zlib-devel openssl openssl-devel pcre pcre-devel geoipupdate gd libXpm libxslt sqlite-devel --skip-broken
          pip install uwsgi
          cd /home/projects/Fisher
          cp -f /home/projects/fisher-secure.py app/config/secure.py
          pipenv install
          /usr/local/python3/bin/uwsgi uwsgi.ini &
          /sbin/init
    privileged: true
    restart: always