version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    hostname: "uptime-kuna"
    user: root
    network_mode: bridge
    volumes:
      - /mnt/data/docker/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8006:3001"
    restart: always
